use anyhow::Result;
use console::style;
use flate2::Compression;
use flate2::write::GzEncoder;
use std::fs::{self, File};
use std::io::{self, Write};
use std::path::Path;
use tar::Builder;

/// Create a single-file Self-Extracting (.sh) installer.
/// It bundles everything in the bundle_dir into a binary payload at the end of a bash script.
pub fn create_sfx(bundle_dir: &str, output_path: &str) -> Result<()> {
    println!(
        "  {} Building single-file SFX installer...",
        style("📦").cyan()
    );

    // 1. Create a tar.gz of the bundle directory in memory
    let mut tar_gz_buffer = Vec::new();
    {
        let enc = GzEncoder::new(&mut tar_gz_buffer, Compression::best());
        let mut tar = Builder::new(enc);
        tar.append_dir_all(".", bundle_dir)?;
        tar.finish()?;
    }

    // 2. Define the shell stub header
    let stub_header = r#"#!/bin/bash
# 3x-ui Offline Self-Extracting Installer
# Generated by xui-offline-builder
set -e

# Configuration
TMP_BASE="/tmp"
INSTALL_DIR="$TMP_BASE/xui-installer-$$"

# Cleanup on exit
trap "rm -rf $INSTALL_DIR" EXIT

echo "------------------------------------------------------------"
echo "  3x-ui Offline Installer (SFX)"
echo "------------------------------------------------------------"

# Find the line where binary data starts
PAYLOAD_LINE=$(awk '/^__BINARY_DATA_BELOW__/ {print NR + 1; exit 0; }' "$0")

if [ -z "$PAYLOAD_LINE" ]; then
    echo "Error: Could not find payload start."
    exit 1
fi

echo "📦 Extracting content..."
mkdir -p "$INSTALL_DIR"

# Extract binary payload
tail -n +$PAYLOAD_LINE "$0" | tar -xz -C "$INSTALL_DIR"

# Run the inner installer
echo "🚀 Starting installation process..."
cd "$INSTALL_DIR"
if [ -f "./install.sh" ]; then
    bash ./install.sh
else
    echo "Error: install.sh not found in bundle."
    exit 1
fi

exit 0
__BINARY_DATA_BELOW__
"#;

    // 3. Write stub header + binary payload to the final .sh file
    let mut f = File::create(output_path)?;
    f.write_all(stub_header.as_bytes())?;
    f.write_all(&tar_gz_buffer)?;

    // 4. Make the output file executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(output_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(output_path, perms)?;
    }

    let size_mb = tar_gz_buffer.len() as f64 / 1024.0 / 1024.0;
    println!(
        "  {} SFX file created: {} ({:.2} MB)",
        style("✓").green(),
        style(output_path).yellow().bold(),
        size_mb
    );

    Ok(())
}

/// Create a standard .tar.gz archive of the bundle.
pub fn create_tar_gz(bundle_dir: &str, output_path: &str) -> Result<()> {
    let f = File::create(output_path)?;
    let enc = GzEncoder::new(f, Compression::best());
    let mut tar = Builder::new(enc);
    tar.append_dir_all(".", bundle_dir)?;
    tar.finish()?;
    Ok(())
}
